### ISSUE TITLE
ChefAPI attribute 'key' was invalid.:

### ISSUE THREAD

**Issue by Ruksov-Andrey** [awslabs/lambda-chef-node-cleanup#23]
Hello

I'm trying to set up a lambda-chef-node-cleanup. And I see a mistake. Could you tell me how to properly do the troubleshooting?

Starting new HTTPS connection (1): kms.eu-west-1.amazonaws.com

An error occurred (AccessDeniedException) when calling the Decrypt operation: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

ChefAPI attribute 'key' was invalid.: ValueError
Traceback (most recent call last):
File "/var/task/main.py", line 70, in handle
with chef.ChefAPI(CHEF_SERVER_URL, get_pem(), USERNAME, ssl_verify=VERIFY_SSL):
File "/var/task/chef/api.py", line 65, in __init__
raise ValueError("ChefAPI attribute 'key' was invalid.")
ValueError: ChefAPI attribute 'key' was invalid.

Thanks

**Comment by Ruksov-Andrey** [comment]
It was decided by adding the kms: Decrypt role
