### ISSUE TITLE
Unauthorized coming back from Chef server

### ISSUE THREAD

**Issue by StubbsPKS** [awslabs/lambda-chef-node-cleanup#8]
I'm trying to get the sample code to work, but I am getting an unauthorized response back from my local Chef server.

It appears as though KMS is working as I can get the pem file name to output after the decrypt.

I have used the pem to successfully search for this node using knife as well, so it leads me to believe that there is an issue with my python code.

I haven't modified anything in the sample code other than the REGION, CHEF_SERVER_URL, and USERNAME variables. I also appear to have the version that is using PyChef 0.3.0 and have verified that the patch to work with Amazon Linux is in rsa.py.

I'm really new to python, so debugging this has been pretty slow going as I cannot figure out how to run the code locally and so I'm uploading to lambda and testing each time. I'm hoping I'm just overlooking something small.

```
START RequestId: e871c3e5-81a7-11e6-b19b-c3d5abdceedc Version: $LATEST
[INFO]  2016-09-23T16:08:04.546Z    e871c3e5-81a7-11e6-b19b-c3d5abdceedc ====================================================
[INFO]  2016-09-23T16:08:04.546Z    e871c3e5-81a7-11e6-b19b-c3d5abdceedc {u'source': [u'aws.ec2'], u'detail': {u'state': [u'terminated'], u'instance-id': u'i-be89e4a8'}, u'detail-type': [u'EC2 Instance State-change Notification']}
[INFO]  2016-09-23T16:08:04.546Z    e871c3e5-81a7-11e6-b19b-c3d5abdceedc ====================================================
[INFO]  2016-09-23T16:08:04.584Z    e871c3e5-81a7-11e6-b19b-c3d5abdceedc Starting new HTTPS connection (1): chef.maned.com
/var/task/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.or...
InsecureRequestWarning)
Unauthorized: ChefServerError
Traceback (most recent call last):
File "/var/task/main.py", line 75, in handle
if len(search) != 0:
File "/var/task/chef/search.py", line 83, in __len__
return len(self.data['rows'])
File "/var/task/chef/search.py", line 60, in data
self._data = self.api[self.url]
File "/var/task/chef/api.py", line 221, in __getitem__
return self.api_request('GET', path)
File "/var/task/chef/api.py", line 217, in api_request
response = self.request(method, path, headers, data)
File "/var/task/chef/api.py", line 207, in request
raise ChefServerError.from_error(response.reason, code=response.status_code)
ChefServerError: Unauthorized
```

**Comment by StubbsPKS** [comment]
Well, I found the issue and it was pretty silly on my part. The user's name is reggie and the configuration had Reggie. Closing this issue.
